server {
    listen 80;
    
    #업로드 허용 크그 (영상 50mb보다 여유롭게)
    client_max_body_size 60m;

    root /usr/share/nginx/html;
    index index.html;

    # 화면 파일
    location /{
        try_files $uri /index.html;
    }

    # /api/... 요청은 백엔드 컨테이너로 전달 (앞의 /apa/는 제외)
    location /api/ {
        proxy_pass http://api:8000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 영상 처리는 오래 걸리므로 대기 시간 늘림 (기본 60초)
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }
}